services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    volumes:
      - ./data:/usr/src/app/data
      - ./notebook:/usr/src/app/notebook
      - ./job:/usr/src/app/job
      - ./output:/usr/src/app/output
  code:
    build:
      dockerfile: ./Dockerfile.notebook
      context: .
    volumes_from:
      - base
    command: [ "code-server", "--auth", "none", "--host", "0.0.0.0", --port, "8080", "/usr/src/app", "--cert-key", "0.0.0.0.pem" ]
    ports:
      - 8080:8080
  ctrees:
    env_file: .env
    build:
      dockerfile: ./Dockerfile.job
      context: .
    volumes_from:
      - base
    command: [".venv/bin/python", "-m", "job.ctrees"]
  neighbours:
    build:
      dockerfile: ./Dockerfile.job
      context: .
    volumes_from:
      - base
    command: [".venv/bin/python", "-m", "job.neighbours"]
  meta_chm:
    build:
      dockerfile: ./Dockerfile.job
      context: .
    volumes_from:
      - base
    command: [".venv/bin/python", "-m", "job.meta_chm"]
  gedi_gee:
      build:
        dockerfile: ./Dockerfile.job
        context: .
      env_file: .env
      volumes_from:
        - base
      command: ["deno",  "run", "-A", "job/gedi_gee/main.ts"]
  eth_chm:
      build:
        dockerfile: ./Dockerfile.job
        context: .
      env_file: .env
      volumes_from:
        - base
      command: ["deno",  "run", "-A", "job/eth_chm/main.ts"]
  embedding:
      build:
        dockerfile: ./Dockerfile.job
        context: .
      env_file: .env
      volumes_from:
        - base
      command: ["deno",  "run", "-A", "job/embedding/main.ts"]
  extract:
      build:
        dockerfile: ./Dockerfile.job
        context: .
      env_file: .env
      volumes_from:
        - base
      command: [".venv/bin/python", "-m", "job.extract"]
  extract_2:
      build:
        dockerfile: ./Dockerfile.job
        context: .
      env_file: .env
      volumes_from:
        - base
      command: [".venv/bin/python", "-m", "job.extract_2"]
  terrain:
      build:
        dockerfile: ./Dockerfile.job
        context: .
      env_file: .env
      volumes_from:
        - base
      command: [".venv/bin/python", "-m", "job.terrain"]
  canopy_density:
      build:
        dockerfile: ./Dockerfile.job
        context: .
      env_file: .env
      volumes_from:
        - base
      command: [".venv/bin/python", "-m", "job.canopy_density"]
  als_canopy_height:
      build:
        dockerfile: ./Dockerfile.job
        context: .
      env_file: .env
      volumes_from:
        - base
      command: [".venv/bin/python", "-m", "job.als_canopy_height"]
  gedi_tree_ratio:
      build:
        dockerfile: ./Dockerfile.job
        context: .
      env_file: .env
      volumes_from:
        - base
      command: [".venv/bin/python", "-m", "job.gedi_tree_ratio"]
  embedding_cog:
      build:
        dockerfile: ./Dockerfile.job
        context: .
      env_file: .env
      volumes_from:
        - base
      command: [".venv/bin/python", "-m", "job.embedding_cog"]
  tessera:
      build:
        dockerfile: ./Dockerfile.job
        context: .
      env_file: .env
      volumes_from:
        - base
      command: [".venv/bin/python", "-m", "job.tessera"]
