FROM eu.gcr.io/ramadhan-s4g/eo-base:latest

RUN apt-get update --fix-missing
RUN apt-get install mkcert

WORKDIR /usr/src/app

COPY private_key.json .

RUN gcloud auth activate-service-account --key-file private_key.json

COPY notebook/requirements.txt .

RUN python3 -m venv .venv && \
  .venv/bin/pip install -r requirements.txt

COPY __init__.py .

ENV GS_NO_SIGN_REQUEST=YES

RUN code-server \
  --install-extension ms-python.python \
  --install-extension ms-toolsai.jupyter \
  --install-extension charliermarsh.ruff \
  --install-extension randomfractalsinc.geo-data-viewer

RUN mkcert localhost
RUN mkcert 0.0.0.0

EXPOSE 8080
